
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: bundle install # runs during prebuild
    command: bundle install && bundle exec rake single
